@echo begin deploy..............................
call mvn install:install-file -DgroupId=com.simbest.boot -DartifactId=simbest-boot-wfdriver -Dversion=0.1 -Dfile=target\simbest-boot-wfdriver.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=E:\01_Work\01_DevSpace\worksapce_github\simbest-maven-repo\repository -DcreateChecksum=true
@echo deploy finished..............................
pause