## @echo begin deploy..............................
## call mvn install:install-file -DgroupId=com.simbest.boot -DartifactId=simbest-boot-cmcc -Dversion=0.1 -Dfile=target\simbest-boot-cmcc.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=E:\01_Work\01_DevSpace\worksapce_github\simbest-maven-repo\repository -DcreateChecksum=true
## @echo deploy finished..............................
## pause

@echo begin deploy..............................
call mvn clean deploy -U -Dmaven.test.skip=true
@echo deploy finished..............................
pause